### ISSUE TITLE
Integrate Losses Calculator backend

### ISSUE THREAD

**Issue by ivignan** [AdTechMedia/adtechmedia-website#195]

**Comment by veronicamacovei** [comment]
**Test Failed**
Acceptance Criteria
1. Website pages  should meet required design - **`Passed`**
2. **Website type** field should include 16 industries options - **`Failed`** "No options available, because of this bug  I can not test the losses calculator functionality "

`Test Blocked by point 2`

---------------------------------------------------------------------- 
3. **Calculate losses** button should redirect to result page -  https://www-dev.adtechmedia.io/calculator-result/ 
4. On result page should be shown The following message  ex: “You are losing 100 $ every month due to ad blocks”. This amount of money should match the function revenue result.
---------------------------------------------------------------------------------------------------
5. **Get Report** button should redirect to confirmation page -  https://www-dev.adtechmedia.io/calculator-confirmation/  -  **`Failed`**
6. **Get Report** button should send an email to user with the information about lost revenue - **`Failed`**
7. Validation for the required fields should be implemented - **`Failed`**
     - Missing full validation for email on https://www-dev.adtechmedia.io/calculator-result/ (safari 
       &chrome&firefox)
     - Missing validation(Safari & Firefox &Chrome) - on page (https://www-
      dev.adtechmedia.io/calculator/) for **Average views per month & Number of banners on a 
      page**  fields
     - Missing validation for **My website link** field
8. Blog’s link should be opened in a new tab on click - **`Passed`**
9. All 3 pages should be responsive - **`Passed`**

**Comment by veronicamacovei** [comment]
**Test Failed**
Acceptance Criteria
1. Website pages  should meet required design - `Passed`
2. **Website type** field should include 16 industries options - `Passed` 
3. **Calculate losses** button should redirect to result page -  https://www-dev.adtechmedia.io/calculator-result/  - `Passed`
4. On result page should be shown The following message  ex: “You are losing 100 $ every month due to ad blocks”. This amount of money should match the function revenue result - `Passed`
5. **Get Report** button should redirect to confirmation page -  https://www-dev.adtechmedia.io/calculator-confirmation/  - `Passed`
6. **Get Report** button should send an email to user with the information about lost revenue - **`Failed`**
7. Blog’s link should be opened in a new tab on click - `Passed`
8. All 3 pages should be responsive - `Passed`

**Comment by veronicamacovei** [comment]
**Test Passed**
Acceptance Criteria
1. Website pages  should meet required design - `Passed`
2. **Website type** field should include 16 industries options - `Passed` 
3. **Calculate losses** button should redirect to result page -  https://www-dev.adtechmedia.io/calculator-result/  - `Passed`
4. On result page should be shown The following message  ex: “You are losing 100 $ every month due to ad blocks”. This amount of money should match the function revenue result - `Passed`
5. **Get Report** button should redirect to confirmation page -  https://www-dev.adtechmedia.io/calculator-confirmation/  - `Passed`
6. **Get Report** button should send an email to user with the information about lost revenue - **`Passed`**
7. Blog’s link should be opened in a new tab on click - `Passed`
8. All 3 pages should be responsive - `Passed`
